export const adminData =  [
    { id: 1, name: "mostafa yasser", email: "email1@email.com", branch: "porsaid", password: "full stack mearn" },
    { id: 2, name: "ahmed ali", email: "email2@email.com", branch: "porfoud", password: "backend engineer" },
    { id: 3, name: "mohamed salah", email: "email3@email.com", branch: "cairo", password: "frontend dev" },
    { id: 4, name: "yasser hassan", email: "email4@email.com", branch: "alex", password: "devops engineer" },
    { id: 5, name: "ibrahim said", email: "email5@email.com", branch: "luxor", password: "data scientist" },
    { id: 6, name: "omar khaled", email: "email6@email.com", branch: "aswan", password: "full stack developer" },
    { id: 7, name: "laila amir", email: "email7@email.com", branch: "mansoura", password: "UX/UI designer" },
    { id: 8, name: "salma yasser", email: "email8@email.com", branch: "giza", password: "mobile developer" },
    { id: 9, name: "ali mohamed", email: "email9@email.com", branch: "sharm", password: "software architect" },
    { id: 10, name: "sara hassan", email: "email10@email.com", branch: "tanta", password: "project manager" },
    { id: 11, name: "fatma said", email: "email11@email.com", branch: "fayoum", password: "cloud engineer" },
    { id: 12, name: "nour eldin", email: "email12@email.com", branch: "beni suef", password: "ai engineer" },
    { id: 13, name: "mona adel", email: "email13@email.com", branch: "minya", password: "blockchain dev" },
    { id: 14, name: "sayed osman", email: "email14@email.com", branch: "sohag", password: "cybersecurity" },
    { id: 15, name: "omar sabry", email: "email15@email.com", branch: "qena", password: "full stack js" },
    { id: 16, name: "khaled abdelrahman", email: "email16@email.com", branch: "assiut", password: "game developer" },
    { id: 17, name: "zeinab mostafa", email: "email17@email.com", branch: "damietta", password: "data engineer" },
    { id: 18, name: "mohsen ali", email: "email18@email.com", branch: "ismailia", password: "network engineer" },
    { id: 19, name: "hassan omar", email: "email19@email.com", branch: "suez", password: "machine learning" },
    { id: 20, name: "amira salah", email: "email20@email.com", branch: "zagazig", password: "qa engineer" },
    { id: 21, name: "yahya farouk", email: "email21@email.com", branch: "kafr el-sheikh", password: "iot developer" },
    { id: 22, name: "noha sameh", email: "email22@email.com", branch: "beni suef", password: "robotics engineer" },
    { id: 23, name: "marwa gamal", email: "email23@email.com", branch: "monofeya", password: "big data engineer" },
    { id: 24, name: "ahmed khaled", email: "email24@email.com", branch: "sharkeya", password: "cloud architect" },
    { id: 25, name: "alaa hamdy", email: "email25@email.com", branch: "qalyubeya", password: "devops specialist" },
  ];