export const requestsData = [  { id: 1,
    name: "mostaha yasser",
    personalImageUrl:"avatar.jpg",
    email: "email@email.com",
    branch: "porsaid",
    track: "full stack mearn",
    graduationYear: "2024",
    nationalId: "1234567892",
    mobile: "+201234567890",
    birthCity: "Cairo",
    faculty: "Computer Science",
    university: "Cairo University",
    program: "9M",
    intake: "43",
    teachingBranches: ["Port Said", "Smart Village"],
    preferredCourses: ["React", "Node.js"],
    jobTitle: "Software Engineer",
    companyName: "Tech Corp",
    experience: "2",
    freelancer: "Yes"
  }
  , {
      id: 2,
      name: "gradut full name",
      personalImageUrl:"avatar.jpg",

      email: "email@email.com",
      branch: "porsaid",
      track: "full stack mearn",
      graduationYear: "2024",
      nationalId: "1234567892",
      mobile: "+201234567890",
      birthCity: "Cairo",
      faculty: "Computer Science",
      university: "Cairo University",
      program: "9M",
      intake: "43",
      teachingBranches: ["Port Said", "Smart Village"],
      preferredCourses: ["React", "Node.js"],
      jobTitle: "Software Engineer",
      companyName: "Tech Corp",
      experience: "2",
      freelancer: "Yes"
    }, {
      id: 3,
      name: "gradut full name",
      personalImageUrl:"avatar.jpg",

      email: "email@email.com",
      branch: "porsaid",
      track: "full stack mearn",
      graduationYear: "2024",
      nationalId: "1234567892",
      mobile: "+201234567890",
      birthCity: "Cairo",
      faculty: "Computer Science",
      university: "Cairo University",
      program: "9M",
      intake: "43",
      teachingBranches: ["Port Said", "Smart Village"],
      preferredCourses: ["React", "Node.js"],
      jobTitle: "Software Engineer",
      companyName: "Tech Corp",
      experience: "2",
      freelancer: "Yes"
    },
    {
      id: 4,
      name: "gradut full name",
      email: "email@email.com",
      personalImageUrl:"avatar.jpg",

      branch: "porsaid",
      track: "full stack mearn",
      graduationYear: "2024",
      nationalId: "1234567892",
      mobile: "+201234567890",
      birthCity: "Cairo",
      faculty: "Computer Science",
      university: "Cairo University",
      program: "9M",
      intake: "43",
      teachingBranches: ["Port Said", "Smart Village"],
      preferredCourses: ["React", "Node.js"],
      jobTitle: "Software Engineer",
      companyName: "Tech Corp",
      experience: "2",
      freelancer: "Yes"
    }
    , {
        id: 5,
        name: "gradut full name",
        email: "email@email.com",
        personalImageUrl:"avatar.jpg",

        branch: "porsaid",
        track: "full stack mearn",
        graduationYear: "2024",
        nationalId: "1234567892",
        mobile: "+201234567890",
        birthCity: "Cairo",
        faculty: "Computer Science",
        university: "Cairo University",
        program: "9M",
        intake: "43",
        teachingBranches: ["Port Said", "Smart Village"],
        preferredCourses: ["React", "Node.js"],
        jobTitle: "Software Engineer",
        companyName: "Tech Corp",
        experience: "2",
        freelancer: "Yes"
      }, {
        id: 6,
        name: "gradut full name",
        email: "email@email.com",
        personalImageUrl:"avatar.jpg",

        branch: "porsaid",
        track: "full stack mearn",
        graduationYear: "2024",
        nationalId: "1234567892",
        mobile: "+201234567890",
        birthCity: "Cairo",
        faculty: "Computer Science",
        university: "Cairo University",
        program: "9M",
        intake: "43",
        teachingBranches: ["Port Said", "Smart Village"],
        preferredCourses: ["React", "Node.js"],
        jobTitle: "Software Engineer",
        companyName: "Tech Corp",
        experience: "2",
        freelancer: "Yes"
      },
  ];
  